const stages=['Captação','Qualificação','Proposta','Negociação','Onboarding','Adoção','Renovação','Expansão'];
let state, page='overview', selected=null, selectedCard=null, query='', filter='Todos', saveQueue=Promise.resolve();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID(), today=()=>new Date().toLocaleDateString('sv-SE');
const seed=()=>({demo:true,accounts:[
 {id:'a1',name:'Orbit',owner:'Você',stage:'Onboarding',goal:'Unificar a operação comercial e reduzir o tempo até o primeiro valor.',people:[{name:'Marina Costa',role:'Decisora · CEO',email:'marina@orbit.example'},{name:'Pedro Lima',role:'Patrocinador · CS',email:'pedro@orbit.example'}],tasks:[{id:'t1',title:'Confirmar critérios de sucesso com Marina',owner:'Você',due:'2026-09-16',done:false,module:'Customer Success'}],notes:[{type:'Reunião',date:'2026-09-12',module:'Customer Success',text:'Kickoff: integração depende da confirmação do responsável técnico. Próximo encontro para validar os marcos de implantação.'},{type:'Ponto promotor',date:'2026-09-12',module:'Customer Success',text:'Pedro destacou a facilidade de reunir o histórico da conta. Sinal qualitativo, não uma pesquisa de satisfação.'}],cards:[{id:'c1',module:'Customer Success',stage:'Onboarding',status:'Contratado',value:1800},{id:'c2',module:'Analytics',stage:'Proposta',status:'Em negociação',value:900}]},
 {id:'a2',name:'Forma',owner:'Você',stage:'Adoção',goal:'Acompanhar a adoção por equipe e demonstrar valor na renovação.',people:[{name:'Bruna Alves',role:'Patrocinadora · Operações',email:'bruna@forma.example'}],tasks:[{id:'t2',title:'Revisar plano de adoção',owner:'Você',due:'2026-09-18',done:false,module:'Customer Success'}],notes:[{type:'Decisão',date:'2026-09-11',module:'Customer Success',text:'Concentrar o primeiro ciclo na equipe de operações. Revisar os resultados no próximo encontro.'}],cards:[{id:'c3',module:'Customer Success',stage:'Adoção',status:'Contratado',value:1400}]},
 {id:'a3',name:'Nimbo',owner:'Você',stage:'Qualificação',goal:'Entender como estruturar a passagem entre vendas e implantação.',people:[],tasks:[],notes:[],cards:[{id:'c4',module:'CRM',stage:'Qualificação',status:'Em negociação',value:1200}]},
 {id:'a4',name:'Linear Labs',owner:'Você',stage:'Expansão',goal:'Expandir o acompanhamento para uma nova unidade de negócio.',people:[],tasks:[],notes:[],cards:[{id:'c5',module:'Analytics',stage:'Expansão',status:'Em negociação',value:800},{id:'c6',module:'CRM',stage:'Renovação',status:'Contratado',value:1500}]},
 {id:'a5',name:'Ponto',owner:'Você',stage:'Captação',goal:'Descobrir as necessidades da operação de clientes.',people:[],tasks:[],notes:[],cards:[{id:'c7',module:'CRM',stage:'Captação',status:'Em negociação',value:0}]}
]});
function toast(text,error=false){$('#toast').textContent=text;$('#toast').className=error?'error':'';$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4500)}
function persist(){const payload=JSON.stringify(state);saveQueue=saveQueue.catch(()=>{}).then(async()=>{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:payload});if(!r.ok)throw Error();toast('Salvo no workspace e no Obsidian')}).catch(()=>toast('Falha ao salvar. Mantenha a página aberta e tente outra alteração.',true));return saveQueue}
const account=()=>state.accounts.find(a=>a.id===selected);
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function modal(title,fields,submit){$('#modalTitle').textContent=title;$('#fields').innerHTML=fields;$('#form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));submit(d);$('#modal').close();render();await persist()};$('#modal').showModal()}
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''} required maxlength="300"></label>`;
const options=(name,label,list,value)=>`<label>${label}<select name="${name}">${list.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;
function newAccount(){modal('Nova empresa',field('name','Nome da empresa')+field('goal','Objetivo do cliente')+field('module','Primeiro módulo')+options('stage','Etapa inicial',stages,'Captação'),d=>state.accounts.push({id:id(),name:d.name.trim(),goal:d.goal,owner:'Você',stage:d.stage,people:[],tasks:[],notes:[],cards:[{id:id(),module:d.module,stage:d.stage,status:'Em negociação',value:0}]}))}
function addCard(){modal('Adicionar módulo',field('module','Módulo do produto')+options('stage','Etapa da jornada',stages,'Captação')+options('status','Situação',['Em negociação','Contratado'],'Em negociação')+field('value','Valor mensal previsto (R$)','0','number'),d=>account().cards.push({id:id(),...d,value:Number(d.value)}))}
function noteForm(type='Reunião'){const a=account();modal('Novo registro',options('type','Tipo',['Reunião','Decisão','Tópico em aberto','Tópico resolvido','Ponto promotor','Ponto detrator'],type)+options('module','Relacionar a',['Geral da empresa',...a.cards.map(c=>c.module)],selectedCard?.module)+`<label>Registro<textarea name="text" required maxlength="8000" placeholder="Contexto, evidência, decisões e próximos passos…"></textarea></label>`,d=>a.notes.unshift({...d,date:today()}))}
function taskForm(){const a=account();modal('Nova atividade',field('title','O que precisa ser feito?')+field('owner','Responsável','Você')+field('due','Prazo',today(),'date')+options('module','Módulo',['Geral da empresa',...a.cards.map(c=>c.module)],selectedCard?.module),d=>a.tasks.push({id:id(),...d,done:false}))}
function peopleForm(){modal('Novo stakeholder',field('name','Nome')+field('role','Papel na conta')+field('email','E-mail','','email'),d=>account().people.push(d))}
function openAccount(a,c){selected=a;selectedCard=state.accounts.find(x=>x.id===a).cards.find(x=>x.id===c)||null;page='detail';render()}
function taskHTML(a,t){return `<div class="task ${t.done?'done':''}"><input aria-label="Concluir ${esc(t.title)}" type="checkbox" data-task="${t.id}" data-account="${a.id}" ${t.done?'checked':''}><div><p>${esc(t.title)}</p><small>${esc(a.name)} · ${esc(t.module)}<br>${esc(t.owner)} · ${esc(t.due)}</small></div></div>`}
function render(){ $('#count').textContent=state.accounts.length;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#breadcrumb').textContent='Meu workspace / '+({overview:'Jornada de clientes',accounts:'Empresas',tasks:'Atividades',journal:'Diário de decisões',detail:account()?.name}[page]);
const title=(h,p)=>`<div class="title-row"><div><div class="page-icon">▤</div><h1>${h}</h1><p class="subtitle">${p}</p></div>${state.demo?'<span class="demo">Dados de demonstração</span>':''}</div>`;
if(page==='overview'){
const cards=state.accounts.flatMap(a=>a.cards.map(c=>({...c,a}))).filter(c=>(c.a.name+' '+c.module).toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||c.status===filter));
$('#app').innerHTML=title('Jornada de clientes','Uma visão compartilhada de cada empresa, módulo e próximo passo.')+`<div class="board-tools"><b>▦ &nbsp; Por etapa</b><span>${cards.length} módulos · ${state.accounts.length} empresas</span><div class="toolbar"><input id="search" aria-label="Buscar empresa ou módulo" placeholder="⌕ Buscar empresa ou módulo" value="${esc(query)}"><select id="filter" aria-label="Filtrar situação">${['Todos','Em negociação','Contratado'].map(s=>`<option ${s===filter?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="board">${stages.map((s,i)=>`<section class="column" data-stage="${s}"><div class="column-title"><span class="stage stage-${i}">${s}</span><span>${cards.filter(c=>c.stage===s).length}</span></div><div class="dropzone">${cards.filter(c=>c.stage===s).map(c=>`<button draggable="true" class="kanban-card" data-open="${c.a.id}" data-card="${c.id}"><span class="card-company">${esc(c.a.name)}</span><strong>${esc(c.module)}</strong><span class="badge ${c.status==='Contratado'?'good':''}">${c.status}</span><p>${esc(c.a.goal)}</p><div class="card-footer"><span>◉ ${esc(c.a.owner)}</span><span>${c.a.tasks.filter(t=>!t.done&&(t.module===c.module||t.module==='Geral da empresa')).length} tarefas</span></div></button>`).join('')}<button class="add-in-column" data-add-stage="${s}">+ Novo módulo</button></div></section>`).join('')}</div><p class="board-hint">Arraste um cartão para mudar a etapa. Abra-o para ver a empresa. Health scores por etapa serão definidos posteriormente.</p>`;
$('#search').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)};$('#filter').onchange=e=>{filter=e.target.value;render()};
document.querySelectorAll('[draggable]').forEach(el=>el.ondragstart=e=>e.dataTransfer.setData('text/plain',JSON.stringify({a:el.dataset.open,c:el.dataset.card})));
document.querySelectorAll('.column').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('dragover')};el.ondragleave=()=>el.classList.remove('dragover');el.ondrop=e=>{e.preventDefault();try{const d=JSON.parse(e.dataTransfer.getData('text/plain'));const a=state.accounts.find(a=>a.id===d.a),c=a.cards.find(c=>c.id===d.c);move(a,c,el.dataset.stage)}catch{} }});
document.querySelectorAll('[data-add-stage]').forEach(b=>b.onclick=()=>{if(!state.accounts.length)return newAccount();modal('Novo módulo na jornada',`<label>Empresa<select name="aid">${state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label>`+field('module','Nome do módulo')+options('status','Situação',['Em negociação','Contratado'],'Em negociação'),d=>state.accounts.find(a=>a.id===d.aid).cards.push({id:id(),module:d.module,status:d.status,stage:b.dataset.addStage,value:0}))});
}else if(page==='detail'){
const a=account(),c=selectedCard;
$('#app').innerHTML=`<button class="back text-button" id="back">← Voltar à jornada</button>`+title(esc(a.name),'Contexto compartilhado da empresa · '+esc(a.owner))+`<div class="detail-layout"><div><div class="panel"><div class="panel-head"><h2>Objetivo da empresa</h2><button id="editAccount" class="text-button">Editar</button></div><div class="body-pad">${esc(a.goal)}</div></div><div class="panel"><div class="panel-head"><h2>Módulos e jornada</h2><button id="addModule" class="text-button">+ Módulo</button></div>${a.cards.map(m=>`<div class="module-row ${m.id===c?.id?'focused':''}"><div><b>${esc(m.module)}</b><small>${m.status} · ${money(m.value)}/mês</small></div><select aria-label="Etapa de ${esc(m.module)}" data-move="${m.id}">${stages.map(s=>`<option ${s===m.stage?'selected':''}>${s}</option>`).join('')}</select><button class="text-button" data-edit-module="${m.id}">Editar</button></div>`).join('')}</div><div class="panel"><div class="panel-head"><h2>Reuniões, tópicos e decisões</h2><button id="addNote" class="text-button">+ Registro</button></div>${a.notes.length?a.notes.map(n=>`<article class="note"><span class="badge">${esc(n.type)}</span><small>${esc(n.date)} · ${esc(n.module)}</small><p>${esc(n.text)}</p></article>`).join(''):'<div class="empty">Registre a primeira conversa e preserve o contexto.</div>'}</div></div><div><div class="panel"><div class="panel-head"><h2>Atividades do CSM</h2><button id="addTask" class="text-button">+ Atividade</button></div>${a.tasks.length?a.tasks.map(t=>taskHTML(a,t)).join(''):'<div class="empty">Nenhuma pendência. Defina o próximo passo.</div>'}</div><div class="panel"><div class="panel-head"><h2>Stakeholders</h2><button id="addPerson" class="text-button">+ Pessoa</button></div>${a.people.length?a.people.map(p=>`<div class="note"><b>${esc(p.name)}</b><small>${esc(p.role)}</small><small>${esc(p.email)}</small></div>`).join(''):'<div class="empty">Quem decide, influencia e usa?</div>'}</div><div class="callout"><b>◇ Saúde por etapa</b><p>Modelo de health score pendente de definição. Registre pontos promotores e detratores com evidências no diário. Ausência de dados não significa insatisfação.</p></div></div></div>`;
$('#back').onclick=()=>{page='overview';render()};$('#addModule').onclick=addCard;$('#addNote').onclick=()=>noteForm();$('#addTask').onclick=taskForm;$('#addPerson').onclick=peopleForm;
$('#editAccount').onclick=()=>modal('Editar empresa',field('name','Nome',a.name)+field('goal','Objetivo',a.goal)+field('owner','Responsável',a.owner),d=>Object.assign(a,d));
document.querySelectorAll('[data-move]').forEach(s=>s.onchange=()=>move(a,a.cards.find(c=>c.id===s.dataset.move),s.value));
document.querySelectorAll('[data-edit-module]').forEach(b=>b.onclick=()=>{const m=a.cards.find(c=>c.id===b.dataset.editModule);modal('Editar módulo',field('module','Nome',m.module)+options('status','Situação',['Em negociação','Contratado'],m.status)+field('value','Valor mensal (R$)',m.value,'number'),d=>{const old=m.module;Object.assign(m,d,{value:Number(d.value)});a.tasks.forEach(t=>{if(t.module===old)t.module=d.module});a.notes.forEach(n=>{if(n.module===old)n.module=d.module})})});
}else if(page==='accounts'){$('#app').innerHTML=title('Empresas','Contexto e relacionamento, em um só lugar.')+`<div class="panel">${state.accounts.map(a=>`<div class="account-row"><span class="logo">${esc(a.name.slice(0,2))}</span><div class="account-info"><b>${esc(a.name)}</b><p>${esc(a.goal)}</p></div><span class="badge">${a.cards.length} módulos</span><button data-open="${a.id}">Abrir ↗</button></div>`).join('')||'<div class="empty">Cadastre sua primeira empresa.</div>'}</div>`;
}else if(page==='tasks'){$('#app').innerHTML=title('Atividades','Compromissos claros, responsáveis e prazos.')+`<div class="panel">${state.accounts.flatMap(a=>a.tasks.map(t=>taskHTML(a,t))).join('')||'<div class="empty">Adicione atividades ao abrir uma empresa.</div>'}</div>`;
}else{$('#app').innerHTML=title('Diário de decisões','A memória do relacionamento, sincronizada com seu cofre Obsidian.')+`<div class="panel">${state.accounts.flatMap(a=>a.notes.map(n=>({a,n}))).sort((x,y)=>y.n.date.localeCompare(x.n.date)).map(({a,n})=>`<article class="note"><span class="badge">${esc(n.type)}</span> <button class="text-button" data-open="${a.id}">${esc(a.name)} ↗</button><small>${esc(n.date)} · ${esc(n.module)}</small><p>${esc(n.text)}</p></article>`).join('')||'<div class="empty">As decisões aparecerão aqui.</div>'}</div>`}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openAccount(b.dataset.open,b.dataset.card));document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{state.accounts.find(a=>a.id===b.dataset.account).tasks.find(t=>t.id===b.dataset.task).done=b.checked;render();persist()});
}
function move(a,c,stage){if(c.stage===stage){render();return}a.notes.unshift({type:'Mudança de etapa',date:today(),module:c.module,text:`${c.stage} → ${stage}`});c.stage=stage;render();persist()}
$('#close').onclick=$('#cancel').onclick=()=>$('#modal').close();$('#addAccount').onclick=newAccount;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
async function init(){try{const r=await fetch('/api/state');if(!r.ok)throw Error();state=await r.json();if(!state){state=seed();await persist()}render()}catch{$('#app').innerHTML='<div class="empty">Não foi possível carregar os dados. Verifique o servidor local e recarregue a página.</div>'}}init();
